dist: trusty
sudo: false

language: go
go:
  - 1.15.x

env:
  - GOFLAGS=-mod=vendor

branches:
  only:
    - master

install:
  - bash scripts/import_key.sh $TRAVIS_REPO_SLUG
  - bash scripts/gogetcookie.sh

script:
  - make test
  - make vet
  - make website-test
  - curl -sfL https://git.io/goreleaser | sh -s -- check

matrix:
  fast_finish: true
  allow_failures:
    - go: master

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
