dist: trusty
sudo: false

language: go
go:
  - 1.14.x
  - master

branches:
  only:
    - master

install:
  - bash scripts/gogetcookie.sh

script:
  - make test
  - make vet
  - make website-test

env:
  - GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
    - go: master

deploy:
  provider: releases
  file: TODO
  edge: true
  on:
    tags: true
